### ISSUE TITLE
Show readme after installation

### ISSUE THREAD

**Issue by montogeek** [vlakarados/devastate#3]
I just installed it and wait for instructions of how to activate it, but is not working or is not implemented.

**Comment by vlakarados** [comment]
There are no instructions, this is a theme and a color scheme, I doubt it needs them. They are available on the main page of the repository and wbond's package page though.

**Comment by montogeek** [comment]
I think in the case the developer just find it navigating packages in Sublime Text, How could it know how to install it?

**Comment by vlakarados** [comment]
Sorry, but do you often install packages like that, without searching for them specifically and without looking for a description? I doubt and I think it's too unsecure to do that because the API allows you to run any type of shell command, such as `rm -rf /`. Anyway, if you wish, you may add a PR with that, I will gladly merge it!

Thanks

**Comment by montogeek** [comment]
Yes, is odd, I have installed packages just reading is description in the Command Palette. I didn't know the API allow to execute any shell command :/.

And about the enhancement, I will try :)
