### ISSUE TITLE
The sidabar looks ugly 

### ISSUE THREAD

**Issue by sebastialonso** [vlakarados/devastate#4]
![ugly_sidebar](https://cloud.githubusercontent.com/assets/3493453/8892271/528b62ca-3326-11e5-819f-e1597697d0e1.png)

Not like the example picture :/
what can I do?

**Comment by gbhatnag** [comment]
I have this same issue.  Seems like ST3 has issues with not being able to change the sidebar background color...

I'm using Build 3083.  Any suggestions/directions/updates to fix this??

**Comment by vlakarados** [comment]
No it's not because of that, most probably it can't find the `.sublime-theme` file, double check you haven't mistyped the path to it. You may try using another theme in the same folder and see if it works without problems. I'm always using the latest ST3 build on Win & Linux, and have never encountered issues like that.

Please try what I have suggested and I'll gladly help if it's not the case!

**Comment by gbhatnag** [comment]
Restarting ST3 after changing the preferences file did the trick.  The sidebar changes do not take affect until after the restart.

I'm all set -- thanks!

**Comment by vlakarados** [comment]
@gbhatnag great! Most likely it's out of my power to fix it without restarting ST.
@sebastialonso can you confirm, in your case the solution was to restart ST too?
